/// Vietnamese text normalization utilities
class VietnameseUtils {
  /// Common Vietnamese keyword mappings (without diacritics → with diacritics)
  /// Comprehensive vocabulary for sharing/marketplace app
  static const Map<String, String> diacriticsMap = {
    // ========== ELECTRONICS ==========
    'may tinh': 'máy tính',
    'maytinh': 'máy tính',
    'laptop': 'laptop',
    'may anh': 'máy ảnh',
    'mayanh': 'máy ảnh',
    'dien thoai': 'điện thoại',
    'dienthoai': 'điện thoại',
    'dien': 'điện',
    'thoai': 'thoại',
    'tivi': 'tivi',
    'ti vi': 'ti vi',
    'tay cam': 'tay cầm',
    'taycam': 'tay cầm',
    'tai nghe': 'tai nghe',
    'tainghe': 'tai nghe',
    'loa': 'loa',
    'bluetooth': 'bluetooth',
    'sac': 'sạc',
    'pin': 'pin',
    'ắc quy': 'ắc quy',
    'acquy': 'ắc quy',
    'may quay': 'máy quay',
    'mayquay': 'máy quay',
    'may chieu': 'máy chiếu',
    'maychieu': 'máy chiếu',
    'may in': 'máy in',
    'mayin': 'máy in',
    'may scan': 'máy scan',
    'mayscan': 'máy scan',

    // ========== FASHION & CLOTHING ==========
    'quan ao': 'quần áo',
    'quanao': 'quần áo',
    'ao': 'áo',
    'quan': 'quần',
    'giay': 'giày',
    'giay the thao': 'giày thể thao',
    'giaythethao': 'giày thể thao',
    'tui xach': 'túi xách',
    'tuixach': 'túi xách',
    'vi': 'ví',
    'tui': 'túi',
    'belt': 'belt',
    'dam': 'đầm',
    'vay': 'váy',
    'khoac': 'khoác',
    'ao khoac': 'áo khoác',
    'aokhoac': 'áo khoác',
    'ao len': 'áo len',
    'aolen': 'áo len',
    'ao thun': 'áo thun',
    'aothun': 'áo thun',
    'somi': 'sơ mi',
    'quan dui': 'quần dùi',
    'quandui': 'quần dùi',
    'quan jean': 'quần jean',
    'quanjean': 'quần jean',
    'quan tay': 'quần tây',
    'quantay': 'quần tây',
    'tay': 'tây',
    'pyjama': 'pyjama',
    'do lot': 'đồ lót',
    'dolot': 'đồ lót',
    'bra': 'bra',
    'bh': 'bh',
    'mat kinh': 'mắt kính',
    'matkinh': 'mắt kính',
    'kinh': 'kính',
    'mu': 'mũ',
    'non': 'nón',
    'scarves': 'scarves',

    // ========== ACCESSORIES & JEWELRY ==========
    'trang suc': 'trang sức',
    'trangsuc': 'trang sức',
    'nhan': 'nhẫn',
    'vong tay': 'vòng tay',
    'vongtay': 'vòng tay',
    'vong': 'vòng',
    'day': 'dây',
    'day chuyem': 'dây chuyền',
    'daychuyem': 'dây chuyền',
    'khoa': 'khóa',
    'dong ho': 'đồng hồ',
    'dongho': 'đồng hồ',
    'mat': 'mắt',
    'cork': 'cork',

    // ========== HOME & FURNITURE ==========
    'do noi that': 'đồ nội thất',
    'donointhat': 'đồ nội thất',
    'ban': 'bàn',
    'ghe': 'ghế',
    'giuong': 'giường',
    'tu': 'tủ',
    'tu quan ao': 'tủ quần áo',
    'tuquanao': 'tủ quần áo',
    'gia': 'giá',
    'ke': 'kế',
    'keo': 'kẹo',
    'den': 'đèn',
    'den ban': 'đèn bàn',
    'denban': 'đèn bàn',
    'den tran': 'đèn trần',
    'dentran': 'đèn trần',
    'lau': 'lau',
    'chim': 'chim',
    'cho': 'chó',
    'meo': 'mèo',
    'co': 'cơ',
    'dung cu': 'dụng cụ',
    'dungcu': 'dụng cụ',
    'muong': 'muỗng',
    'nia': 'nĩa',
    'noi': 'nồi',
    'chao': 'chảo',
    'la': 'la',
    'tap': 'tập',

    // ========== KITCHEN & DINING ==========
    'do an': 'đồ ăn',
    'doan': 'đồ ăn',
    'thuc pham': 'thực phẩm',
    'thucpham': 'thực phẩm',
    'mon an': 'món ăn',
    'monan': 'món ăn',
    'nuoc': 'nước',
    'nuoc uong': 'nước uống',
    'nuocuong': 'nước uống',
    'tra': 'trà',
    'ca phe': 'cà phê',
    'caphe': 'cà phê',
    'sua': 'sữa',
    'banh': 'bánh',
    'mut': 'mứt',
    'do uong': 'đồ uống',
    'douong': 'đồ uống',
    'bia': 'bia',
    'ruou': 'rượu',
    'ruou vang': 'rượu vang',
    'ruouvang': 'rượu vang',
    'kem': 'kem',
    'da': 'dâu',
    'tao': 'táo',
    'cam': 'cam',
    'chanh': 'chanh',
    'thom': 'thơm',

    // ========== BOOKS & EDUCATION ==========
    'sach': 'sách',
    'sach hoc': 'sách học',
    'sachhoc': 'sách học',
    'trai': 'trái',
    'tieu thuyet': 'tiểu thuyết',
    'tieuthuyết': 'tiểu thuyết',
    'truyen': 'truyện',
    'tap chi': 'tạp chí',
    'tapchi': 'tạp chí',
    'truyen tranh': 'truyện tranh',
    'truyentranh': 'truyện tranh',
    'vo': 'vở',
    'to': 'tờ',
    've': 'về',
    'may': 'máy',

    // ========== TOYS & GAMES ==========
    'do choi': 'đồ chơi',
    'dochoi': 'đồ chơi',
    'tro choi': 'trò chơi',
    'trochoi': 'trò chơi',
    'lua': 'lửa',
    'gau bong': 'gấu bông',
    'gaubong': 'gấu bông',
    'boneka': 'boneka',
    'lego': 'lego',
    'xe dua': 'xe đua',
    'xedua': 'xe đua',
    'xe': 'xe',
    'robot': 'robot',
    'may bay': 'máy bay',
    'maybay': 'máy bay',
    'bo ban': 'bộ ban',
    'boban': 'bộ ban',
    'co vua': 'cờ vua',
    'covua': 'cờ vua',
    'dan': 'dán',
    'the': 'thẻ',

    // ========== SPORTS & OUTDOOR ==========
    'the thao': 'thể thao',
    'thethao': 'thể thao',
    'dung cu the thao': 'dụng cụ thể thao',
    'dungcuthethao': 'dụng cụ thể thao',
    'bong': 'bóng',
    'bong ro': 'bóng rổ',
    'bongrob': 'bóng rổ',
    'bong ban': 'bóng bàn',
    'bongban': 'bóng bàn',
    'tai': 'tay',
    'ca nhan': 'cá nhân',
    'canhan': 'cá nhân',
    'tham yoga': 'thảm yoga',
    'thamyoga': 'thảm yoga',
    'ba lo': 'ba lô',
    'balo': 'ba lô',
    'net': 'nét',
    'dun': 'dùn',

    // ========== BEAUTY & PERSONAL CARE ==========
    'my pham': 'mỹ phẩm',
    'mypham': 'mỹ phẩm',
    'dau': 'dầu',
    'dau goi': 'dầu gội',
    'daugoi': 'dầu gội',
    'dau xa': 'dầu xả',
    'dauxa': 'dầu xả',
    'xa': 'xả',
    'xa phong': 'xà phòng',
    'xaphong': 'xà phòng',
    'sua tam': 'sữa tắm',
    'suatam': 'sữa tắm',
    'kem duong': 'kem dưỡng',
    'kemduong': 'kem dưỡng',
    'kem chong nang': 'kem chống nắng',
    'kemchongnang': 'kem chống nắng',
    'nuoc hoa': 'nước hoa',
    'nuochoa': 'nước hoa',
    'nuoc tay': 'nước tây',
    'nuoctay': 'nước tây',
    'chi': 'chí',
    'mascara': 'mascara',
    'son': 'son',
    'phan': 'phấn',
    'kem chi': 'kem chí',
    'kemchi': 'kem chí',

    // ========== HEALTH & MEDICINE ==========
    'thuoc': 'thuốc',
    'thuoc uong': 'thuốc uống',
    'thuocuong': 'thuốc uống',
    'thuoc boi': 'thuốc bôi',
    'thuocboi': 'thuốc bôi',
    'bang dan': 'băng dán',
    'bangdan': 'băng dán',
    'bang': 'băng',
    'nhiet ke': 'nhiệt kế',
    'nhietke': 'nhiệt kế',
    'may do': 'máy đo',
    'maydo': 'máy đo',
    'huyet ap': 'huyết áp',
    'huyetap': 'huyết áp',
    'may tro': 'máy trợ',
    'maytro': 'máy trợ',
    'goi ngoai': 'gói ngoài',
    'goingoai': 'gói ngoài',
  };

  /// Normalize Vietnamese text by:
  /// 1. Trimming spaces
  /// 2. Converting to lowercase
  /// 3. Removing multiple spaces (replace with single space)
  /// 4. Adding diacritics if keyword is in the map
  static String normalizeKeyword(String keyword) {
    // Trim and lowercase
    String normalized = keyword.trim().toLowerCase();

    // Remove multiple spaces (normalize to single space)
    normalized = normalized.replaceAll(RegExp(r'\s+'), ' ');

    // Try to find mapping with spaces first
    if (diacriticsMap.containsKey(normalized)) {
      normalized = diacriticsMap[normalized]!;
    } else {
      // Try without spaces
      String noSpaces = normalized.replaceAll(RegExp(r'\s+'), '');
      if (diacriticsMap.containsKey(noSpaces)) {
        normalized = diacriticsMap[noSpaces]!;
      }
    }

    return normalized;
  }

  /// Check if keyword needs diacritics
  static bool needsDiacritics(String keyword) {
    return diacriticsMap.containsKey(keyword.toLowerCase().trim());
  }
}
